import { AmplifyProvider } from "../components/amplifyProvider";
import AppContextProvider from "../lib/appContext";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <AmplifyProvider>{children}</AmplifyProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
