import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PlantCard from '../components/plantCard'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <i>S E P A L</i>
        </h1>

        <p className={styles.description}>
         Bring blooms to where you've put down roots.
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <PlantCard
            thumb="/monstera.webp"
            sciName="Monstera Deliciosa"
            nickname="Frankenstein's Monstera"
            room="Dining Room"
            instructions = {{
              water: "Flood & Drain every 2 weeks. Mist leaves 2x weekly",
              light: "Indirect"
            }}
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
